package com.mycompany.app;

import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;
import com.microsoft.azure.sdk.iot.service.Device;
import com.microsoft.azure.sdk.iot.service.RegistryManager;

import java.io.IOException;
import java.net.URISyntaxException;

public class App{

        private static final String connectionString = "HostName=iothub-0f09bdec.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=WIyFAoGQDJKye5R6JIaxD2YaD9OQXjQ3f9XlpS5b7o8=";
        private static final String deviceId = "chouams";

    public static void main( String[] args ) throws IOException, URISyntaxException, Exception
    {
        RegistryManager registryManager = RegistryManager.createFromConnectionString(connectionString);

// Create a device that's enabled by default,
// with an autogenerated key.
        Device device = Device.createFromId(deviceId, null, null);
        try {
            device = registryManager.addDevice(device);
        } catch (IotHubException iote) {
            // If the device already exists.
            try {
                device = registryManager.getDevice(deviceId);
            } catch (IotHubException iotf) {
                iotf.printStackTrace();
            }
        }

// Display information about the
// device you created.
        System.out.println( "Ein Device wurde erstellt!" );
        System.out.println("Device Id: " + device.getDeviceId());
        System.out.println("Device key: " + device.getPrimaryKey());

    }
}
